//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public int PatientId { get; set; }
        [Required]
        public string First_Name { get; set; }
        [Required]
        public string Last_Name { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Date_Of_Birth { get; set; }
        public string Patient_Address { get; set; }
        public string Tel_No { get; set; }
        public string Email_Address { get; set; }
        [Required]
        public string Diabetic_Type { get; set; }
        public string Comments { get; set; }
        public string Retinal_Image { get; set; }
    }
}
